services:
  salesforce-db:
    image: postgres:15-alpine
    container_name: salesforce-db
    restart: always
    environment:
      - POSTGRES_USER=sf_user
      - POSTGRES_PASSWORD=sf_password
      - POSTGRES_DB=salesforce_local
    ports:
      - "6000:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_salesForceData:/var/lib/postgresql/data
    networks:
      - PmrSalesForce

networks:
  PmrSalesForce:
    external: true

volumes:
  postgres_salesForceData: