server:
  port: ${SERVER_PORT:9090}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME:muralip.wk@gmail.com}
    #password: ${USER_PASSWORD:bcrx narv fwgc mtrq}
    password: ${USER_PASSWORD:bcrx narv fwgc mtrq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#ibsu sjee uzgn rmjs
#https://myaccount.google.com/u/1/apppasswords?rapt=AEjHL4NroP8EQVJXi5sIvlc2eyh6fT-xxJZzsvV9ofwayiAsWIQM8stpZ45X2TEcQuApq0ZMeGIUOk4av2dJhf4FxlTtyTr6iYjJjG698nVHhp5IsmP9s84

app:
  storage:
    use-localstack: ${WRITE_TO_LOCALSTACK:true}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.dailycodebuffer.springbootdemo: ${LOGGING_LEVEL:DEBUG}

info:
  app:
    name: Doctors And Patients real DB
    version: 1.0.0
    description:  Doctors And Patients real DB